services: 
  postgres: 
    container_name: postgres
    image: postgres:latest 
    restart: always 
    environment: # Environment variables to be passed to the container
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
    ports: 
        - "5432:5432"
  
  frontend:
    image: ${DOCKER_USERNAME}/cicd-demo-frontend:latest
    container_name: frontend
    ports:
      - '80:3000'
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  backend:
    image: ${DOCKER_USERNAME}/cicd-demo-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    restart: always