name: Build and deploy to Docker Hub
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'


      - name: Docker compose build
        run: docker-compose build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub
        run: |
          docker tag ci-cd-example_frontend:latest ${{ secrets.DOCKER_USERNAME }}/cicd-demo-frontend:latest
          docker tag ci-cd-example_backend:latest ${{ secrets.DOCKER_USERNAME }}/cicd-demo-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo-backend:latest
          docker images